name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t rallycoding/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true rallycoding/react-test npm test

      - run: docker build -t mdwahidali/multi-container-client ./client
      - run: docker build -t mdwahidali/multi-container-nginx ./nginx
      - run: docker build -t mdwahidali/multi-container-server ./server
      - run: docker build -t mdwahidali/multi-container-worker ./worker

      - run: docker push mdwahidali/multi-container-client
      - run: docker push mdwahidali/multi-container-nginx
      - run: docker push mdwahidali/multi-container-server
      - run: docker push mdwahidali/multi-container-worker
